dist: focal
sudo: false
language: c
os:
  - linux
addons:
  apt:
    packages:
      - shellcheck
      - cmake
env:
  global:
  - LC_ALL: C
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio ../hardware/keyboardio
## We delete the Bundle's version of Kaleidoscope, and symlink ourselves in.
## This makes sure we're using the current version of the library.
  - rm -rf ../hardware/keyboardio/avr/libraries/Kaleidoscope
  - ln -s $(pwd) ../hardware/keyboardio/avr/libraries/Kaleidoscope
script:
  - unset CC
  - make cpplint BOARD_HARDWARE_PATH=$(pwd)/../hardware
  - make travis-install-arduino BOARD_HARDWARE_PATH=$(pwd)/../hardware
  - (cd ../hardware/keyboardio && make prepare-virtual)
  - make -C tests all BOARD_HARDWARE_PATH=$(pwd)/../hardware ARDUINO_PATH="$(pwd)/arduino-1.8.13"
  - rm -rf .kaleidoscope-build-cache
  - make travis-test KALEIDOSCOPE_TEMP_PATH=$(pwd)/.kaleidoscope-build-cache BOARD_HARDWARE_PATH=$(pwd)/../hardware
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true
  directories:
    - .kaleidoscope-build-cache
    - .ccache
