dist: trusty
sudo: false
os:
  - linux
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio hardware/keyboardio
script:
  - make travis-test BOARD_HARDWARE_PATH=$(pwd)/hardware
notifications:
  irc:
    channels:
      - "chat.freenode.net#keyboardio"
    use_notice: true
    skip_join: true
    template:
      - "%{repository_name}/%{branch} %{commit} by %{author}: %{commit_subject} %{build_url} %{message}"
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true
